DROP TABLE IF EXISTS deliveries;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS partners;

CREATE TABLE partners (
    partner_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name   VARCHAR(255) NOT NULL,
    inn            VARCHAR(12)  NOT NULL UNIQUE,
    contact_email  VARCHAR(255) UNIQUE,
    phone          VARCHAR(20),
    rating         DECIMAL(2,1)
);

CREATE TABLE products (
    product_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name   VARCHAR(255) NOT NULL
);

CREATE TABLE deliveries (
    delivery_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id     INTEGER NOT NULL REFERENCES partners(partner_id) ON DELETE RESTRICT,
    product_id     INTEGER NOT NULL REFERENCES products(product_id) ON DELETE RESTRICT,
    delivery_date  DATE NOT NULL,
    quantity       INTEGER NOT NULL CHECK (quantity > 0),
    total_amount   DECIMAL(12,2) NOT NULL CHECK (total_amount >= 0)
);
