BEGIN;

CREATE TABLE IF NOT EXISTS product_types (
    product_type_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name        VARCHAR(255) NOT NULL UNIQUE,
    coefficient      DECIMAL(6,2) NOT NULL CHECK (coefficient > 0)
);

CREATE TABLE IF NOT EXISTS material_types (
    material_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name        VARCHAR(255) NOT NULL UNIQUE,
    defect_percent   DECIMAL(5,2) NOT NULL CHECK (defect_percent >= 0)
);

INSERT INTO product_types (product_type_id, type_name, coefficient) VALUES
    (1, 'Ламинат', 2.35),
    (2, 'Массивная доска', 5.15),
    (3, 'Паркетная доска', 4.34),
    (4, 'Пробковое покрытие', 1.50)
ON CONFLICT (product_type_id) DO UPDATE SET
    type_name = EXCLUDED.type_name,
    coefficient = EXCLUDED.coefficient;

INSERT INTO material_types (material_type_id, type_name, defect_percent) VALUES
    (1, 'Ламинированные панели', 0.10),
    (2, 'Нержавеющая сталь', 0.30),
    (3, 'Полимерная пленка', 0.55)
ON CONFLICT (material_type_id) DO UPDATE SET
    type_name = EXCLUDED.type_name,
    defect_percent = EXCLUDED.defect_percent;

SELECT setval(pg_get_serial_sequence('product_types', 'product_type_id'), (SELECT MAX(product_type_id) FROM product_types));
SELECT setval(pg_get_serial_sequence('material_types', 'material_type_id'), (SELECT MAX(material_type_id) FROM material_types));

COMMIT;
